### ISSUE TITLE
typeshed stubs

### ISSUE THREAD

**Issue by srittau** [thombashi/DateTimeRange#32]
This is just a short note to inform you that we added static type stubs for datetimerange to [typeshed](/python/typeshed), contributed by @snallapa. See python/typeshed#3845 for more information.

**Comment by thombashi** [comment]
Thank you for your information.
I appreciate that news.

**Comment by hauntsaninja** [comment]
Let me know if you're interested in a PR that merged these type annotations into DateTimeRange :-)

**Comment by thombashi** [comment]
@hauntsaninja 
It sounds good.
PR would be welcome.
