### ISSUE TITLE
[Feature Request] Create DateTimeRange from String

### ISSUE THREAD

**Issue by noamsgl** [thombashi/DateTimeRange#38]
hi

Love the package.

It would be very useful to be able to construct a DateTimeRange from a single string (e.g. from the string representation), as in:
`dtr = DateTimeRange("2008-01-03T06:55:29 - 2008-01-03T07:55:29")
`

**Comment by thombashi** [comment]
@noamsgl 
Thank you for your feedback.

You can construct a `DateTimeRange` from a single string since `DateTimeRange 1.2.0`:

```pycon
>>> from datetimerange import DateTimeRange
>>> DateTimeRange.from_range_text("2008-01-03T06:55:29 - 2008-01-03T07:55:29")
2008-01-03T06:55:29 - 2008-01-03T07:55:29
```
