### ISSUE TITLE
conda-forge recipe

### ISSUE THREAD

**Issue by kthyng** [thombashi/DateTimeRange#42]
Hi and thanks for this useful package! I am using it in another project, which I would like to have installable on conda-forge. So, I am planning to make a conda-forge recipe for this today or soon. I'll post back here when I am done.

**Comment by kthyng** [comment]
Working on it here: https://github.com/conda-forge/staged-recipes/pull/20217

**Comment by thombashi** [comment]
@kthyng 
Thank you for letting me know.
It would be greatly appreciated.

The PR you created has already been merged, so I will close the issue.

**Comment by kthyng** [comment]
You are welcome!
