### ISSUE TITLE
Substraction from `end_datetime` with negative `relativedelta(days=-3, weeks=-2, ... )` ?

### ISSUE THREAD

**Issue by 4l1fe** [thombashi/DateTimeRange#44]
Hey. I'm looking for a way to create a range where a few points left that are computed starting from an end datetime, not start datetime.

Something like this
```python
dr = DateTimeRange(datetime.now(timezone.utc), datetime.now(timezone.utc) + timedelta(days=60))
dr.range(relativedelta(days=-7))
```

Now, obviously, i get the error
```
ValueError: invalid step: expect greater than 0, actual=relativedelta(days=-7)
```

Is there a workaround for such the case?
What do you think about implementing the substraction from `end_datetime`?

**Comment by thombashi** [comment]
DateTimeRange supported reverse traversing range as follows:

```py
start = datetime.now(timezone.utc)
end = start + timedelta(days=60)
dr = DateTimeRange(end, start)
dr.range(relativedelta(days=-7))
```

However, this is not correctly worked at DateTimeRange<2.
You can use that DateTimeRange 2.0.0 or newer.

**Comment by 4l1fe** [comment]
That's great. I tested it out with version `2.0` and it works.

Good job! 👍🏻
