### ISSUE TITLE
tox -e lint fails for me on master

### ISSUE THREAD

**Issue by hauntsaninja** [thombashi/DateTimeRange#46]
```
lint: commands[3]> pylama
datetimerange/__init__.py:129:101 E501 line too long (106 > 100 characters) [pycodestyle]
datetimerange/__init__.py:876:101 E501 line too long (105 > 100 characters) [pycodestyle]
```

It looks like this is not run in CI https://github.com/thombashi/DateTimeRange/blob/03b2c0ecb8c8d4f3bb7dbc5b3d014bbb0c52c9ad/.github/workflows/tests.yml#L44

**Comment by thombashi** [comment]
Thank you for your feedback.
I fixed lint errors and added a lint job to CI.
