### ISSUE TITLE
Daylight Savings Time

### ISSUE THREAD

**Issue by tweyter** [thombashi/DateTimeRange#8]
>>>time_range = DateTimeRange("2015-11-01T00:00:00-0400", "2015-11-01T12:00:00-0400")
>>>time_range.timedelta
datetime.timedelta(0, 43200)  # 12 hours
Should be 13 hours, because of the time zone change that occurred at 2am.
dateutil does not handle time zone aware times as well as pytz does. This will affect your timedelta method as well as __eq__, __ne__ etc.

**Comment by thombashi** [comment]
I have fixed the problem.

```pycon
>>> from datetimerange import DateTimeRange
>>> time_range = DateTimeRange("2015-11-01T00:00:00-0400", "2015-11-01T12:00:00-0400")
>>> time_range.timedelta
datetime.timedelta(0, 46800)  # 13 hours
```

Thank you for the feedback.

**Comment by tweyter** [comment]
どういたしまして
